theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
title: "ノート：心理学史"
description: "むかし公務員試験のために作ったノートです。暇があればアップデートしたい。"
twitter:
  username: cosine_135
defaults:
  - scope:
      path: ""
    values:
      image: 
          path: "/img/icon.jpg"
