theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
title: ノート：心理学史
twitter:
  username: cosine_135
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: https://pbs.twimg.com/profile_images/829256869051035649/KJdvlrfP_400x400.jpg
