theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
title: "ノート：心理学史"
description: "@cosine_135 が公務員試験のために昔作ったノートです。暇があればアップデートしたい。"
twitter:
  username: cosine_135
defaults:
  - scope:
      path: ""
    values:
      image: 
          path: "/img/icon.jpg"
